export { ProxyType, anyId, type AnyIdConfig, type ProxyTypeName } from './any-id'
export { billPayment, type BillPaymentConfig } from './bill-payment'
export { slipVerify, type SlipVerifyConfig } from './slip-verify'
export { trueMoney, type TrueMoneyConfig } from './true-money'
export { trueMoneySlipVerify, type TrueMoneySlipVerifyConfig } from './true-money-slip-verify'
export { botBarcode, type BotBarcodeConfig } from './bot-barcode'
